In [1]:
import numpy as np

In [6]:
python_list = [1,2,3,4,5]

numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2) # array([1., 2., 3., 4., 5.])

[1. 2. 3. 4. 5.]


In [3]:
numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)
print(numpy_bool_array)

[False  True  True False False]


In [4]:
type(numpy_bool_array)

numpy.ndarray

In [5]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
np_to_list = numpy_array_from_list2.tolist()
print(type (np_to_list))
print('一维数组:', np_to_list)
print('二维数组: ', numpy_two_dimensional_list.tolist())

<class 'list'>
一维数组: [1.0, 2.0, 3.0, 4.0, 5.0]
二维数组:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [8]:
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) # <class 'tuple'>
print('python_tuple: ', python_tuple) # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple)

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [9]:
numpy_bool_array.shape

(5,)

In [10]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


In [11]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print(numpy_array_from_list.dtype)
print('除法: ', numpy_array_from_list / 2)
print(numpy_array_from_list)

原始数组:  [1 2 3 4 5]
int64
除法:  [0.5 1.  1.5 2.  2.5]
[1 2 3 4 5]


In [12]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('指数: ', numpy_array_from_list ** 2)
print('指数: ', np.power(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
指数:  [ 1  4  9 16 25]
指数:  [ 1  4  9 16 25]


In [17]:
numpy_int_arr = np.array([1, 2, 3, 4])
numpy_float_arr = np.array([1.1, 2.0, 3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1, 2, 3], dtype=bool)

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)
print(numpy_bool_arr)

int64
float64
bool
[ True  True False  True  True  True]


In [19]:
numpy_float_arr = np.array([1, 2, 3, 4], dtype='float')
print(numpy_float_arr.astype(int))
numpy_float_arr

[1 2 3 4]


array([1., 2., 3., 4.])

In [20]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('第一列:', first_column)
print('第二列:', second_column)
print('第三列: ', third_column)

第一列: [1 4 7]
第二列: [2 5 8]
第三列:  [3 6 9]


In [21]:
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])
third_array = np.array([7, 8, 9])

In [23]:
horizontal_concat = np.hstack((first_array, second_array, third_array))
print(horizontal_concat)

[1 2 3 4 5 6 7 8 9]


In [24]:
vertical_concat = np.vstack((first_array, second_array, third_array))
print(vertical_concat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [27]:
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
print(numpy_zeroes)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
np.array([(1,2,3), (4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
three_d_array = np.array([[[2,3,4],[1,2,3],[1,4,5]],[[6,5,7],[1,4,5],[3,4,5]]])
print(three_d_array)

[[[2 3 4]
  [1 2 3]
  [1 4 5]]

 [[6 5 7]
  [1 4 5]
  [3 4 5]]]


In [34]:
three_d_array.shape

(2, 3, 3)

In [36]:
one_d_array = three_d_array.flatten()
print(three_d_array.shape)
print(one_d_array.shape)

(2, 3, 3)
(18,)


In [38]:
np.random.random(5)

array([0.04980443, 0.14861101, 0.012191  , 0.55927448, 0.33917239])

In [39]:
import random

In [40]:
random.random()

0.07627790855541627

In [ ]:
random.randint(0,11)

TypeError: Random.randint() got an unexpected keyword argument 'size'

In [46]:
help(random)

Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.13/library/random.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
        bytes
        -----
               uniform bytes (values between 0 and 255)

        integers
        --------
               uniform within range

        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation

        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               l

In [47]:
normal_array = np.random.normal(79, 15, (5,5))
print(normal_array)

[[65.94341158 69.53928641 80.45937273 72.77756966 75.60621233]
 [87.2553823  89.34284583 78.00533137 43.41111789 77.38430631]
 [59.36349835 72.97964889 74.98767055 72.86323097 76.480476  ]
 [97.58923803 49.42580317 79.46852931 96.48108797 75.20514991]
 [88.80968386 71.36566106 75.65909109 75.35578589 50.25923717]]


In [48]:
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))

In [49]:
print(four_by_four_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
type(four_by_four_matrix)

numpy.matrix

In [ ]:
np.ones((4,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.asarray(four_by_four_matrix)[2] = 2
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])

In [54]:
type(four_by_four_matrix)

numpy.matrix

In [57]:
type(np.asarray(four_by_four_matrix))

numpy.ndarray

In [56]:
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])

In [58]:
# creating list using range(starting, stop, step)
lst = range(0, 11, 2)
lst

range(0, 11, 2)

In [59]:
for l in lst:
    print(l)

0
2
4
6
8
10


In [60]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [62]:
ls = list(np.arange(0,11,2))

In [63]:
ls[0]

np.int64(0)

In [64]:
type(ls[0])

numpy.int64

In [65]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [69]:
np_normal_dis = np.random.normal(5, 0.5, 100)
print(np_normal_dis.shape)
## min, max, mean, median, sd
print('min: ', np_normal_dis.min())
print('max: ', np_normal_dis.max())
print('mean: ',np_normal_dis.mean())
print('sd: ', np_normal_dis.std())

(100,)
min:  3.4384134663636194
max:  5.959771001157906
mean:  4.938675789423186
sd:  0.49490662842281397


In [70]:
help(random.choice)

Help on method choice in module random:

choice(seq) method of random.Random instance
    Choose a random element from a non-empty sequence.



In [72]:
random.choices([1,2,3,4,5],k=9)

[5, 4, 2, 3, 2, 5, 2, 4, 2]

In [73]:
np_normal_dis = np.random.normal(5, 0.5, 1000)

In [1]:
from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [3]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [4]:
%pip freeze

anyio==4.9.0
appnope==0.1.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.5
attrs==25.3.0
babel==2.17.0
beautifulsoup4==4.13.4
bleach==6.2.0
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.4.1
comm==0.2.2
debugpy==1.8.14
decorator==5.2.1
defusedxml==0.7.1
distlib==0.3.9
executing==2.2.0
fastjsonschema==2.21.1
filelock==3.18.0
fqdn==1.5.1
h11==0.14.0
httpcore==1.0.8
httpx==0.28.1
idna==3.10
ipykernel==6.29.5
ipython==9.1.0
ipython_pygments_lexers==1.1.1
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.6
json5==0.12.0
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter-events==0.12.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.15.0
jupyter_server_terminals==0.5.3
jupyterlab==4.4.0
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
MarkupSafe==3.0.2
matplotlib-inline==0.1.7
mistune==3.1.3
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
notebook==7.

In [6]:
import numpy as np
import sys

# Python list of lists
py_list = [[1, 2, 3], [4, 5, 6]]
print(sum(sys.getsizeof(row) for row in py_list) + sys.getsizeof(py_list))  # 估算总内存

# Equivalent NumPy array
np_array = np.array(py_list)
print(np_array.nbytes)  # 只返回数组中元素占用的字节数

248
48
